---
framework: ${{ secrets.Mocha_Framework }}
postMerge: 
  env: 
    envname11: postmerge1
    envname12: postmerge2
  pattern: 
    - "./test/**/*.spec.ts"
    - ${{ secrets.Pattern }}
  strategy: 
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     env:
         envname1: "prerun"
         testing: Key testing string ${{ secrets.AWS_Dummy_Key }} done
     command:
        - ${{ secrets.NPM_CI }}
postRun:
     command:
        - node --${{ secrets.Version }}
version: 2.0
