---
framework: mocha
postMerge: 
  env: 
    envname11: postmerge1
    envname12: postmerge2
  pattern: 
    - "./test/**/*.spec.ts"
  strategy: 
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     env:
         envname1: "prerun"
         testing: ${{ secrets.AWS_Dummy_Key }}
     command:
        - ${{ secrets.NPM_CI }}
postRun:
     command:
        - node --version
version: 2.0
