---
framework: mocha
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     env:
         envname1: "prerun"
     secret:
         testing: "{{secretvalue}}" 
     command:
        - npm ci
postRun:
     command:
        - node --version
version: 2.0
