---
framework: mocha
postMerge: 
  pattern: 
    - "./test/**/*.spec.ts"
  strategy:
    isactive: 0
    threshold: 2
    name: after_n_commits
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     command:
        - npm ci
postRun:
     command:
        - node --version
version: 2.1
